// packages/ark/wheel-picker/src/react/wheel-picker-context.tsx
import type { ReactNode } from "react"
import { type UseWheelPickerContext, useWheelPickerContext } from "./use-wheel-picker-context"

export interface WheelPickerContextProps {
  children: (context: UseWheelPickerContext) => ReactNode
}

export const WheelPickerContext = (props: WheelPickerContextProps) => props.children(useWheelPickerContext())

// packages/ark/wheel-picker/src/svelte/wheel-picker-context.svelte
<script module lang="ts">
  import type { Snippet } from "svelte"
  import type { UseWheelPickerContext } from "./use-wheel-picker-context"

  export interface WheelPickerContextProps {
    render?: Snippet<[UseWheelPickerContext]>
  }
</script>

<script lang="ts">
  import { useWheelPickerContext } from "./use-wheel-picker-context"

  const { render }: WheelPickerContextProps = $props()
  const api = useWheelPickerContext()
</script>

{@render render?.(api)}
