// packages/ark/wheel-picker/src/react/wheel-picker-item.tsx
import { ark, type HTMLProps, type PolymorphicProps } from "@ark-ui/react/factory"
import * as wheelPicker from "@isbatak/zag-wheel-picker"
import { mergeProps } from "@zag-js/react"
import { forwardRef } from "react"
import { useWheelPickerContext } from "./use-wheel-picker-context"

export interface WheelPickerItemBaseProps extends wheelPicker.ItemProps, PolymorphicProps {}
export interface WheelPickerItemProps extends HTMLProps<"li">, WheelPickerItemBaseProps {}

export const WheelPickerItem = forwardRef<HTMLLIElement, WheelPickerItemProps>((props, ref) => {
  const [itemProps, localProps] = wheelPicker.splitItemProps(props)
  const api = useWheelPickerContext()
  const mergedProps = mergeProps(api.getItemProps(itemProps), localProps)

  return <ark.li {...mergedProps} ref={ref} />
})

WheelPickerItem.displayName = "WheelPickerItem"

// packages/ark/wheel-picker/src/svelte/wheel-picker-item.svelte
<script module lang="ts">
  import type { ItemProps } from "@isbatak/zag-wheel-picker"
  import type { Assign } from "../types.js"
  import type { HTMLProps, PolymorphicProps, RefAttribute } from "./types.js"

  export interface WheelPickerItemBaseProps extends ItemProps, PolymorphicProps<"li">, RefAttribute {}
  export interface WheelPickerItemProps extends Assign<HTMLProps<"li">, WheelPickerItemBaseProps> {}
</script>

<script lang="ts">
  import { Ark } from "@ark-ui/svelte"
  import * as wheelPicker from "@isbatak/zag-wheel-picker"
  import { mergeProps } from "@zag-js/svelte"
  import { useWheelPickerContext } from "./use-wheel-picker-context.js"

  let { ref = $bindable(null), ...props }: WheelPickerItemProps = $props()
  const [itemProps, localProps] = $derived(wheelPicker.splitItemProps(props))
  const api = useWheelPickerContext()
  const mergedProps = $derived(mergeProps(api().getItemProps(itemProps), localProps))
</script>

<Ark as="li" bind:ref {...mergedProps} />
