// packages/ark/wheel-picker/src/react/wheel-picker-highlight-item.tsx
import { ark, type HTMLProps, type PolymorphicProps } from "@ark-ui/react/factory"
import * as wheelPicker from "@isbatak/zag-wheel-picker"
import { mergeProps } from "@zag-js/react"
import { forwardRef } from "react"
import { useWheelPickerContext } from "./use-wheel-picker-context"

export interface WheelPickerHighlightItemBaseProps extends wheelPicker.ItemProps, PolymorphicProps {}
export interface WheelPickerHighlightItemProps extends HTMLProps<"li">, WheelPickerHighlightItemBaseProps {}

export const WheelPickerHighlightItem = forwardRef<HTMLLIElement, WheelPickerHighlightItemProps>((props, ref) => {
  const [itemProps, localProps] = wheelPicker.splitItemProps(props)
  const api = useWheelPickerContext()
  const mergedProps = mergeProps(api.getHighlightItemProps(itemProps), localProps)

  return <ark.li {...mergedProps} ref={ref} />
})

WheelPickerHighlightItem.displayName = "WheelPickerHighlightItem"

// packages/ark/wheel-picker/src/svelte/wheel-picker-highlight-item.svelte
<script module lang="ts">
  import type { ItemProps } from "@isbatak/zag-wheel-picker"
  import type { Assign } from "../types"
  import type { HTMLProps, PolymorphicProps, RefAttribute } from "./types"

  export interface WheelPickerHighlightItemBaseProps extends ItemProps, PolymorphicProps<"li">, RefAttribute {}
  export interface WheelPickerHighlightItemProps extends Assign<HTMLProps<"li">, WheelPickerHighlightItemBaseProps> {}
</script>

<script lang="ts">
  import { Ark } from "@ark-ui/svelte"
  import * as wheelPicker from "@isbatak/zag-wheel-picker"
  import { mergeProps } from "@zag-js/svelte"
  import { useWheelPickerContext } from "./use-wheel-picker-context"

  let { ref = $bindable(null), ...props }: WheelPickerHighlightItemProps = $props()
  const [itemProps, localProps] = $derived(wheelPicker.splitItemProps(props))
  const api = useWheelPickerContext()
  const mergedProps = $derived(mergeProps(api().getHighlightItemProps(itemProps), localProps))
</script>

<Ark as="li" bind:ref {...mergedProps} />
