// packages/ark/wheel-picker/src/svelte/wheel-picker-highlight-item-group.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from "./types.js"

  export interface WheelPickerHighlightItemGroupBaseProps extends PolymorphicProps<"ul">, RefAttribute {}
  export interface WheelPickerHighlightItemGroupProps extends HTMLProps<"ul">, WheelPickerHighlightItemGroupBaseProps {}
</script>

<script lang="ts">
  import { Ark } from "@ark-ui/svelte"
  import { mergeProps } from "@zag-js/svelte"
  import { useWheelPickerContext } from "./use-wheel-picker-context.js"

  let { ref = $bindable(null), ...props }: WheelPickerHighlightItemGroupProps = $props()
  const api = useWheelPickerContext()
  const mergedProps = $derived(mergeProps(api().getHighlightItemGroupProps(), props))
</script>

<Ark as="ul" bind:ref {...mergedProps} />

// packages/ark/wheel-picker/src/react/wheel-picker-highlight-item-group.tsx
import { ark, type HTMLProps, type PolymorphicProps } from "@ark-ui/react/factory"
import { mergeProps } from "@zag-js/react"
import { forwardRef } from "react"
import { useWheelPickerContext } from "./use-wheel-picker-context"

export interface WheelPickerHighlightItemGroupBaseProps extends PolymorphicProps {}
export interface WheelPickerHighlightItemGroupProps extends HTMLProps<"ul">, WheelPickerHighlightItemGroupBaseProps {}

export const WheelPickerHighlightItemGroup = forwardRef<HTMLUListElement, WheelPickerHighlightItemGroupProps>(
  (props, ref) => {
    const api = useWheelPickerContext()
    const mergedProps = mergeProps(api.getHighlightItemGroupProps(), props)

    return <ark.ul {...mergedProps} ref={ref} />
  },
)

WheelPickerHighlightItemGroup.displayName = "WheelPickerHighlightItemGroup"
