// apps/storybook-preact/src/wheel-picker/basic.tsx
import { wheelPicker as wheelPickerRecipe } from "@isbatak/panda-ds/recipes"
import { frameworkCollection, type WheelPickerControls } from "@isbatak/storybook-shared"
import * as wheelPicker from "@isbatak/zag-wheel-picker"
import { normalizeProps, useMachine } from "@zag-js/preact"
import { useId } from "preact/hooks"

const styles = wheelPickerRecipe()

export interface BasicProps extends Partial<WheelPickerControls> {
  onValueChange?: (details: wheelPicker.ValueChangeDetails) => void
}

export function Basic(props: BasicProps) {
  const service = useMachine(wheelPicker.machine, {
    id: useId(),
    collection: frameworkCollection,
    defaultValue: "react",
    name: "framework",
    ...props,
  })

  const api = wheelPicker.connect(service, normalizeProps)

  return (
    <main className="wheel-picker">
      <div {...api.getRootProps()} className={styles.root}>
        <label {...api.getLabelProps()} className={styles.label}>
          Framework
        </label>

        <div {...api.getControlProps()} className={styles.control}>
          <div {...api.getViewportProps()} className={styles.viewport}>
            <ul {...api.getItemGroupProps()} className={styles.itemGroup}>
              {api.items.map(({ item, index, key }) => (
                <li key={key} {...api.getItemProps({ item, index })} className={styles.item}>
                  {item.label}
                </li>
              ))}
            </ul>

            <div {...api.getHighlightProps()} className={styles.highlight}>
              <ul {...api.getHighlightItemGroupProps()} className={styles.highlightItemGroup}>
                {api.highlightItems.map(({ item, index, key }) => (
                  <li key={key} {...api.getHighlightItemProps({ item, index })} className={styles.highlightItem}>
                    {item.label}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        <select {...api.getHiddenSelectProps()}>
          {frameworkCollection.items.map((item) => (
            <option key={item.value} value={item.value} disabled={item.disabled}>
              {item.label}
            </option>
          ))}
        </select>
      </div>

      <output data-testid="value">Selected: {api.valueAsString}</output>
    </main>
  )
}

// apps/storybook-solid/src/wheel-picker/basic.tsx
import { wheelPicker as wheelPickerRecipe } from "@isbatak/panda-ds/recipes"
import { frameworkCollection, type WheelPickerControls } from "@isbatak/storybook-shared"
import * as wheelPicker from "@isbatak/zag-wheel-picker"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { For, Index, createMemo, createUniqueId } from "solid-js"

const styles = wheelPickerRecipe()

export interface BasicProps extends Partial<WheelPickerControls> {
  onValueChange?: (details: wheelPicker.ValueChangeDetails) => void
}

export function Basic(props: BasicProps) {
  const id = createUniqueId()
  const service = useMachine(wheelPicker.machine, () => ({
    id,
    collection: frameworkCollection,
    defaultValue: "react",
    name: "framework",
    ...props,
  }))
  const api = createMemo(() => wheelPicker.connect(service, normalizeProps))

  return (
    <main class="wheel-picker">
      <div {...api().getRootProps()} class={styles.root}>
        <label {...api().getLabelProps()} class={styles.label}>
          Framework
        </label>
        <div {...api().getControlProps()} class={styles.control}>
          <div {...api().getViewportProps()} class={styles.viewport}>
            <ul {...api().getItemGroupProps()} class={styles.itemGroup}>
              <Index each={api().items}>
                {(entry) => (
                  <li {...api().getItemProps(entry())} class={styles.item}>
                    {entry().item.label}
                  </li>
                )}
              </Index>
            </ul>
            <div {...api().getHighlightProps()} class={styles.highlight}>
              <ul {...api().getHighlightItemGroupProps()} class={styles.highlightItemGroup}>
                <Index each={api().highlightItems}>
                  {(entry) => (
                    <li {...api().getHighlightItemProps(entry())} class={styles.highlightItem}>
                      {entry().item.label}
                    </li>
                  )}
                </Index>
              </ul>
            </div>
          </div>
        </div>
        <select {...api().getHiddenSelectProps()}>
          <For each={frameworkCollection.items}>
            {(item) => (
              <option value={item.value} disabled={item.disabled}>
                {item.label}
              </option>
            )}
          </For>
        </select>
      </div>
      <output data-testid="value">Selected: {api().valueAsString}</output>
    </main>
  )
}
