// apps/storybook-solid/src/wheel-picker/multiple.tsx
import { hourCollection, meridiemCollection, minuteCollection } from "@isbatak/storybook-shared"
import type * as wheelPicker from "@isbatak/zag-wheel-picker"
import { createSignal } from "solid-js"
import { Picker } from "./picker"

const toLabel = (details: wheelPicker.ValueChangeDetails) => details.item?.label ?? ""

export function Multiple() {
  const [hour, setHour] = createSignal("09")
  const [minute, setMinute] = createSignal("41")
  const [meridiem, setMeridiem] = createSignal("AM")

  return (
    <main class="wheel-picker">
      <div class="wheel-picker-group" role="group" aria-label="Time">
        <Picker
          label="Hour"
          collection={hourCollection}
          defaultValue="9"
          infinite
          name="hour"
          hiddenSelect
          onValueChange={(details) => setHour(toLabel(details))}
        />
        <Picker
          label="Minute"
          collection={minuteCollection}
          defaultValue="41"
          infinite
          name="minute"
          hiddenSelect
          onValueChange={(details) => setMinute(toLabel(details))}
        />
        <Picker
          label="Meridiem"
          collection={meridiemCollection}
          defaultValue="AM"
          name="meridiem"
          hiddenSelect
          onValueChange={(details) => setMeridiem(toLabel(details))}
        />
      </div>
      <output data-testid="value">
        Selected time: {hour()}:{minute()} {meridiem()}
      </output>
    </main>
  )
}

// apps/storybook-react/src/wheel-picker/multiple.tsx
import { hourCollection, meridiemCollection, minuteCollection } from "@isbatak/storybook-shared"
import * as wheelPicker from "@isbatak/zag-wheel-picker"
import { normalizeProps, useMachine } from "@zag-js/react"
import { useId } from "react"

export function Multiple() {
  const id = useId()
  const hourService = useMachine(wheelPicker.machine, {
    id: `${id}:hour`,
    collection: hourCollection,
    defaultValue: "9",
    infinite: true,
    name: "hour",
  })
  const minuteService = useMachine(wheelPicker.machine, {
    id: `${id}:minute`,
    collection: minuteCollection,
    defaultValue: "41",
    infinite: true,
    name: "minute",
  })
  const meridiemService = useMachine(wheelPicker.machine, {
    id: `${id}:meridiem`,
    collection: meridiemCollection,
    defaultValue: "AM",
    name: "meridiem",
  })

  const hourApi = wheelPicker.connect(hourService, normalizeProps)
  const minuteApi = wheelPicker.connect(minuteService, normalizeProps)
  const meridiemApi = wheelPicker.connect(meridiemService, normalizeProps)
  const pickers = [
    { api: hourApi, collection: hourCollection, label: "Hour" },
    { api: minuteApi, collection: minuteCollection, label: "Minute" },
    { api: meridiemApi, collection: meridiemCollection, label: "Meridiem" },
  ]

  return (
    <main className="wheel-picker">
      <div className="wheel-picker-group" role="group" aria-label="Time">
        {pickers.map(({ api, collection, label }) => (
          <div key={label} {...api.getRootProps()}>
            <label className="sr-only" {...api.getLabelProps()}>
              {label}
            </label>
            <div {...api.getControlProps()}>
              <div {...api.getViewportProps()}>
                <ul {...api.getItemGroupProps()}>
                  {api.items.map(({ item, index, key }) => (
                    <li key={key} {...api.getItemProps({ item, index })}>
                      {item.label}
                    </li>
                  ))}
                </ul>

                <div {...api.getHighlightProps()}>
                  <ul {...api.getHighlightItemGroupProps()}>
                    {api.highlightItems.map(({ item, index, key }) => (
                      <li key={key} {...api.getHighlightItemProps({ item, index })}>
                        {item.label}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>

            <select {...api.getHiddenSelectProps()}>
              {collection.items.map((item) => (
                <option key={item.value} value={item.value}>
                  {item.label}
                </option>
              ))}
            </select>
          </div>
        ))}
      </div>

      <output data-testid="value">
        Selected time: {hourApi.valueAsString}:{minuteApi.valueAsString} {meridiemApi.valueAsString}
      </output>
    </main>
  )
}
