// packages/ark/wheel-picker/src/svelte/wheel-picker-hidden-select.svelte
<script module lang="ts">
  import type { Assign } from "../types.js"
  import type { HTMLProps, PolymorphicProps, RefAttribute } from "./types.js"

  export interface WheelPickerHiddenSelectBaseProps extends PolymorphicProps<"select">, RefAttribute {}
  export interface WheelPickerHiddenSelectProps extends Assign<HTMLProps<"select">, WheelPickerHiddenSelectBaseProps> {}
</script>

<script lang="ts">
  import { Ark } from "@ark-ui/svelte"
  import { mergeProps } from "@zag-js/svelte"
  import { useWheelPickerContext } from "./use-wheel-picker-context.js"

  let { ref = $bindable(null), ...props }: WheelPickerHiddenSelectProps = $props()
  const api = useWheelPickerContext()
  const mergedProps = $derived(mergeProps(api().getHiddenSelectProps(), props))
</script>

<Ark as="select" bind:ref {...mergedProps}>
  {#each api().collection.items as item (api().collection.getItemValue(item))}
    <option value={api().collection.getItemValue(item) ?? ""} disabled={api().collection.getItemDisabled(item)}>
      {api().collection.stringifyItem(item)}
    </option>
  {/each}
</Ark>

// packages/ark/wheel-picker/src/solid/wheel-picker-hidden-select.tsx
import { ark, type HTMLProps, type PolymorphicProps } from "@ark-ui/solid/factory"
import { mergeProps } from "@zag-js/solid"
import { Index } from "solid-js"
import { useWheelPickerContext } from "./use-wheel-picker-context"

export interface WheelPickerHiddenSelectBaseProps extends PolymorphicProps<"select"> {}
export interface WheelPickerHiddenSelectProps extends HTMLProps<"select">, WheelPickerHiddenSelectBaseProps {}

export const WheelPickerHiddenSelect = (props: WheelPickerHiddenSelectProps) => {
  const api = useWheelPickerContext()
  const mergedProps = mergeProps(() => api().getHiddenSelectProps(), props)

  return (
    <ark.select {...mergedProps}>
      <Index each={api().collection.items}>
        {(item) => (
          <option
            value={api().collection.getItemValue(item()) ?? ""}
            disabled={api().collection.getItemDisabled(item())}
          >
            {api().collection.stringifyItem(item())}
          </option>
        )}
      </Index>
    </ark.select>
  )
}
