// packages/ark/wheel-picker/src/react/wheel-picker-context.tsx
import type { ReactNode } from "react"
import { type UseWheelPickerContext, useWheelPickerContext } from "./use-wheel-picker-context"

export interface WheelPickerContextProps {
  children: (context: UseWheelPickerContext) => ReactNode
}

export const WheelPickerContext = (props: WheelPickerContextProps) => props.children(useWheelPickerContext())

// packages/ark/wheel-picker/src/solid/wheel-picker-context.tsx
import type { JSX } from "solid-js"
import { type UseWheelPickerContext, useWheelPickerContext } from "./use-wheel-picker-context"

export interface WheelPickerContextProps {
  children: (context: UseWheelPickerContext) => JSX.Element
}

export const WheelPickerContext = (props: WheelPickerContextProps) => props.children(useWheelPickerContext())
